/uwb_node:
  ros__parameters:

    ####################################################################
    # Choose a decentralized scheduling scheme.
    ####################################################################
    # scheduler: "slow" 
    scheduler: "common_list"
    #scheduler: "hot_potato" # not supported yet

    ####################################################################
    frequency: 100 # ranging frequency in hz
    max_id: 12 # Max possible module ID in the area (used for neighbor discovery)

    ####################################################################
    # Sequence of range measurements. Used for "common_list" scheduler
    ####################################################################
    from_id_sequence: [9,9,11]
    to_id_sequence:   [3,12,3]
    # from_id_sequence: [1, 3, 4, 2, 6, 5, 1, 2, 3, 4, 5, 6, 1, 3, 4, 2, 5, 6, 1, 2, 6, 3, 4, 5]
    # to_id_sequence:   [4, 6, 5, 3, 1, 4, 3, 6, 1, 1, 2, 3, 5, 2, 6, 4, 3, 2, 6, 5, 4, 5, 2, 1]