
    ####################################################################
    # Sequence of range measurements. Used for "common_list" scheduler
    ####################################################################
    sequence:
      - from_id: 1
        to_id: 4
      - from_id: 3
        to_id: 6
      - from_id: 4
        to_id: 5
      - from_id: 2
        to_id: 3
      - from_id: 6
        to_id: 1
      - from_id: 5
        to_id: 4

      - from_id: 1
        to_id: 3
      - from_id: 2
        to_id: 6
      - from_id: 3
        to_id: 1
      - from_id: 4
        to_id: 1
      - from_id: 5
        to_id: 2
      - from_id: 6
        to_id: 3

      - from_id: 1
        to_id: 5
      - from_id: 3
        to_id: 2
      - from_id: 4
        to_id: 6
      - from_id: 2
        to_id: 4
      - from_id: 5
        to_id: 3
      - from_id: 6
        to_id: 2

      - from_id: 1
        to_id: 6
      - from_id: 2
        to_id: 5
      - from_id: 6
        to_id: 4
      - from_id: 3
        to_id: 5
      - from_id: 4
        to_id: 2
      - from_id: 5
        to_id: 1